server:
  port: 8081

spring:
  application:
    name: shop-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600s
      key-prefix: "shop:cache:"
      use-key-prefix: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
